#!/usr/bin/env python3
"""Adds the Play Integrity Capacitor plugin to the generated android/ project.

android/ is regenerated by `npx cap add android` on every Codemagic build, so this runs from package.json's
"capacitor:sync:after" hook (i.e. at the end of `npx cap sync android`, after the pinch-zoom MainActivity patch)
rather than being committed. It:
  1. copies native/PlayIntegrityPlugin.java.tmpl next to MainActivity.java (package filled in),
  2. registers the plugin in MainActivity.onCreate (before super.onCreate, as Capacitor requires),
  3. adds the com.google.android.play:integrity dependency to android/app/build.gradle.
Fails loudly if any file doesn't look the way it expects, like the other patch steps.
"""
import os, re, sys, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE = os.path.join(ROOT, "native", "PlayIntegrityPlugin.java.tmpl")
INTEGRITY_DEP = "implementation 'com.google.android.play:integrity:1.4.0'"

# Runs from package.json's capacitor:sync:after hook, so it also fires for iOS syncs and for the Admin app. Skip those quietly.
if not os.path.isdir("android/app/src/main/java"):
    print("No android/ project here (iOS sync?) - skipping Play Integrity plugin")
    sys.exit(0)
main_files = glob.glob("android/app/src/main/java/**/MainActivity.java", recursive=True)
if len(main_files) != 1:
    sys.exit("ERROR: expected exactly one MainActivity.java under android/app/src/main/java, found %d" % len(main_files))
main_path = main_files[0]
with open(main_path) as f:
    main = f.read()

m = re.search(r"^package\s+([\w.]+);", main, re.M)
if not m:
    sys.exit("ERROR: no package line in " + main_path)
package = m.group(1)
if package.endswith(".notebuilderadmin"):
    print("Admin app (loads the live /admin page, no ads) - skipping Play Integrity plugin")
    sys.exit(0)

# 1. plugin class
with open(TEMPLATE) as f:
    plugin = f.read().replace("__PACKAGE__", package)
plugin_path = os.path.join(os.path.dirname(main_path), "PlayIntegrityPlugin.java")
with open(plugin_path, "w") as f:
    f.write(plugin)

# 2. register it in MainActivity
if "PlayIntegrityPlugin" in main:
    print("MainActivity already registers PlayIntegrityPlugin")
else:
    if "onCreate(" in main:
        sys.exit("ERROR: MainActivity.java already has an onCreate - add registerPlugin(PlayIntegrityPlugin.class) before super.onCreate by hand and update this script.")
    head = "public class MainActivity extends BridgeActivity {"
    if head not in main:
        sys.exit("ERROR: MainActivity.java doesn't contain the expected class declaration - the template may have changed.")
    if "import android.os.Bundle;" not in main:
        main = re.sub(r"^(package\s+[\w.]+;)", r"\1\n\nimport android.os.Bundle;", main, count=1, flags=re.M)
    main = main.replace(
        head,
        head + "\n    @Override\n    public void onCreate(Bundle savedInstanceState) {\n"
        "        registerPlugin(PlayIntegrityPlugin.class);\n"
        "        super.onCreate(savedInstanceState);\n    }\n",
        1,
    )
    with open(main_path, "w") as f:
        f.write(main)

# 3. gradle dependency
gradle_path = "android/app/build.gradle"
with open(gradle_path) as f:
    gradle = f.read()
if "com.google.android.play:integrity" not in gradle:
    new, n = re.subn(r"(?m)^(dependencies\s*\{)", r"\1\n    " + INTEGRITY_DEP, gradle, count=1)
    if n != 1:
        sys.exit("ERROR: couldn't find the dependencies block in " + gradle_path)
    with open(gradle_path, "w") as f:
        f.write(new)

print("Play Integrity plugin added (package %s)" % package)
